### ISSUE TITLE
Using compiled macos binary error when running kha project

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/Kromx#4]
Following instruction in readme to compile kromx, when building and running kha project, I get vertex color and linker errors:
```
GLSL compiler error: vertexColor
GLSL compiler error: vertexColor
GLSL linker error: 
GLSL compiler error: vertexColor
GLSL compiler error: vertexColor
GLSL linker error: 
GLSL compiler error: vertexColor
GLSL compiler error: vertexColor
GLSL linker error: 
GLSL compiler error: vertexColor
GLSL compiler error: vertexColor
GLSL linker error: 
GLSL compiler error: vertexColor
GLSL compiler error: vertexColor
GLSL linker error: 
GLSL compiler error: vertexColor
GLSL compiler error: vertexColor
GLSL linker error: 
```
(yes, `-g opengl` flag is given)

**Comment by luboslenco** [comment]
It apparently no longer works on latest macos + xcode, because opengl. You may get it to work using older xcode 9 but if I recall that no longer works on latest macos. Should get resolved once transition to metal happens.
