### ISSUE TITLE
XMLHttpRequests are not possible [Feature Request]

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/Kromx#5]
For example the [server_stream](https://github.com/armory3d/armory_examples/tree/master/server_stream) example is only possible in Browser right now. It would be important to have XMLHttpRequests in future versions of Krom. 
Right now it does not work because `untyped __js__("typeof XMLHttpRequest")` always returns undefined in Krom (I think?), which is why an error is thrown.

**Comment by luboslenco** [comment]
Investigate at https://github.com/Kode/Krom/issues/100.
