### ISSUE TITLE
Trying to access getPixels() of a kha Image produces a crash

### ISSUE THREAD

**Issue by N8n5h** [armory3d/Kromx#6]
Issue found by @QuantumCoderQC in the armory3d forum.

![image](https://user-images.githubusercontent.com/42382648/74619058-fe8aec80-5112-11ea-9bf0-1e213e3dcb29.png)

the crash error: 
```#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ffc0a454a10
==== C stack trace ===============================

    /.../Armory SDK//Krom/Krom() [0xa36273]
```
With a bit of testing I pinpointed it to this line https://github.com/armory3d/Kromx/blob/93c7a3c80ea7aeb820c68d8e5de9ba04c9400a9c/Sources/main.cpp#L1740
it seems that trying to obtain the Value() produces the crash.

project for quick testing [getpixels.zip](https://github.com/armory3d/Kromx/files/4211543/getpixels.zip)

**Comment by luboslenco** [comment]
This should apply to all Kha targets, to get image pixels set `readable` argument to true:

```hx
notifyOnInit(function() {
	iron.data.Data.getImage("tex1.png", function(img: kha.Image) {
		var p = img.getPixels();
		trace(p != null);
	}, true); // readable
});
```

Also make sure to access the image inside the `getImage` callback, it may be called later than the code below it.

Putting your example into [armory_examples](https://github.com/armory3d/armory_examples) is welcome!
