### ISSUE TITLE
ios wip

### ISSUE THREAD

**Issue by ChristianHohlfeld** [armory3d/Kromx#8]
Latest Xcode runtime issue on IOS (yeah, I know, it's still wip).
After successfully compiling the app on ios (main.cpp line 3305):
-> Could not load krom.js, aborting.

Did I miss something or is the file missing inside the app package bundle on ios?
Any help appreciated. Thank you.

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorpaint/issues/343.
